### ISSUE TITLE
稀疏化训练完后并没有生成 cfg 文件，直接剪枝报错

### ISSUE THREAD

**Issue by lguopeng** [coldlarry/YOLOv3-complete-pruning#103]
其中 prune_tiny_yolo.py 文件的 opt 参数如下
    model_def = "cfg/yolov3-tiny.cfg"
    data_config = "cfg/oxfordhand.data"
    model = 'weights/last.pt'

报错：
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prune_tiny_yolo.py", line 38, in <module>
    origin_model_metric = eval_model(model)
  File "prune_tiny_yolo.py", line 33, in <lambda>
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
  File "E:\python\YOLOv3-complete-pruning-master\test.py", line 69, in test
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "D:\programs\Python38\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "D:\programs\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\programs\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "D:\programs\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "D:\programs\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 8948, 244, 10520, 3460) exited unexpectedly

**Comment by lguopeng** [comment]
1
