### ISSUE TITLE
NameError: name 'parse_data_cfg' is not defined

### ISSUE THREAD

**Issue by matianyun** [coldlarry/YOLOv3-complete-pruning#104]
我在执行正常训练的命令的时候
`
python3 train.py --data data/oxfordhand.data --batch-size 32 --accumulate 1 --weights weights/yolov3.weights --cfg cfg/yolov3-hand.cfg
`
提示如上错误
`
Traceback (most recent call last):
  File "train.py", line 479, in <module>
    train()  # train normally
  File "train.py", line 75, in train
    data_dict = parse_data_cfg(data)
NameError: name 'parse_data_cfg' is not defined
`
请问这是什么问题呢？

**Comment by Noisercontrollers** [comment]
你这个我也遇到过，直接在复制一次函数名字过来就可以
