### ISSUE TITLE
prune_tiny_yolo.py错误

### ISSUE THREAD

**Issue by Mayzy** [coldlarry/YOLOv3-complete-pruning#24]
你好，我在运行prune_tiny_yolo.py时，只显示了进度条栏，但一直是0，程序不报错也没有进行下去，一直停在那里，想知道是哪里出了问题，希望得到您的解答。
另外，稀疏训练时我用的是yolov3-tiny.cfg，剪枝时用这个报错，换成yolov3-tiny-hand.cfg后不报错，但出现了上述问题。
等待您的解答，谢谢。

**Comment by coldlarry** [comment]
您好，稀疏化Tiny时，使用yolov3-tiny-hand.cfg 这个配置文件。剪枝时使用稀疏化后生成的.weights文件及yolov3-tiny-hand.cfg。

**Comment by Mayzy** [comment]
好的，谢谢您。目前这个问题解决了。但是我在得到剪枝后的cfg和weights文件后，在darknet下进行测试时图片一张都检测不到，请问您遇到过这个问题吗

**Comment by ZhaoMonica** [comment]
@coldlarry 
Hello, you can get the weights file after pruning, but not the cfg file. How do you solve this problem?

**Comment by Super-six-java** [comment]
> 您好，稀疏化Tiny时，使用yolov3-tiny-hand.cfg 这个配置文件。剪枝时使用稀疏化后生成的.weights文件及yolov3-tiny-hand.cfg。

作者你好，我使用yolov3-tiny.cfg 能正常训练出来 ，但是剪枝时报模型错误，当我换成 yolov3-tiny-hand.cfg ，并将 prune 换成 2 之后运行 train.py 后 直接报断言错误
 `WARNING: smart bias initialization failure.
WARNING: smart bias initialization failure.
Traceback (most recent call last):
  File "E:/qianru/YOLOv3-complete-pruning/train.py", line 482, in <module>
    train()  # train normally
  File "E:/qianru/YOLOv3-complete-pruning/train.py", line 135, in train
    cutoff = load_darknet_weights(model, weights)
  File "E:\qianru\YOLOv3-complete-pruning\models.py", line 394, in load_darknet_weights
    assert ptr == len(weights)        
AssertionError`
