### ISSUE TITLE
yolo-tiny剪枝错误

### ISSUE THREAD

**Issue by Whatsetsthisend** [coldlarry/YOLOv3-complete-pruning#28]
首先非常感谢作者的开源，但是我在使用tiny剪枝时遇到了错误，BrokenPipeError: [Errno 32] Broken pipe  RuntimeError:  The "freeze_support()" line can be omitted if the program大致是线程之类的错误，我用的使自己训练的四分类网络就是标准的yolo-tiny只更改了yolo层符合我的四个输出。望作者解答

**Comment by Whatsetsthisend** [comment]
Traceback (most recent call last):
  File "prune_tiny_yolo.py", line 28, in <module>
    data_config = parse_data_cfg(opt.data_config)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\utils\parse_config.py", line 32, in parse_data_cfg
    with open(path, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'cfg/voc.data'

(python36) F:\image_work\jianzhi\YOLOv3-complete-pruning-master>python prune_tiny_yolo.py
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "F:\anaconda\envs\python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "F:\anaconda\envs\python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "F:\anaconda\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\prune_tiny_yolo.py", line 38, in <module>
    origin_model_metric = eval_model(model)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\prune_tiny_yolo.py", line 33, in <lambda>
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\test.py", line 69, in test
Traceback (most recent call last):
  File "prune_tiny_yolo.py", line 38, in <module>
    origin_model_metric = eval_model(model)
  File "prune_tiny_yolo.py", line 33, in <lambda>
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\test.py", line 69, in test
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "F:\anaconda\envs\python36\lib\site-packages\tqdm\std.py", line 1093, in __iter__
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "F:\anaconda\envs\python36\lib\site-packages\tqdm\std.py", line 1093, in __iter__
    for obj in iterable:
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    for obj in iterable:
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
    return _DataLoaderIter(self)
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "F:\anaconda\envs\python36\lib\multiprocessing\process.py", line 105, in start
    w.start()
    self._popen = self._Popen(self)
  File "F:\anaconda\envs\python36\lib\multiprocessing\process.py", line 105, in start
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 322, in _Popen
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    return Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\anaconda\envs\python36\lib\multiprocessing\reduction.py", line 60, in dump
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:00<?, ?it/s]
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:02<?, ?it/s]

**Comment by Whatsetsthisend** [comment]
raceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "prune_tiny_yolo.py", line 38, in <module>
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    origin_model_metric = eval_model(model)
    exitcode = _main(fd)
  File "prune_tiny_yolo.py", line 33, in <lambda>
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 114, in _main
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
    prepare(preparation_data)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\test.py", line 69, in test
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 225, in prepare
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\anaconda\envs\python36\lib\site-packages\tqdm\std.py", line 1093, in __iter__
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    for obj in iterable:
    run_name="__mp_main__")
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
  File "F:\anaconda\envs\python36\lib\runpy.py", line 263, in run_path
    return _DataLoaderIter(self)
    pkg_name=pkg_name, script_name=fname)
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
  File "F:\anaconda\envs\python36\lib\runpy.py", line 96, in _run_module_code
    w.start()
    mod_name, mod_spec, pkg_name, script_name)
  File "F:\anaconda\envs\python36\lib\multiprocessing\process.py", line 105, in start
  File "F:\anaconda\envs\python36\lib\runpy.py", line 85, in _run_code
    self._popen = self._Popen(self)
    exec(code, run_globals)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 223, in _Popen
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\prune_tiny_yolo.py", line 38, in <module>
    return _default_context.get_context().Process._Popen(process_obj)
    origin_model_metric = eval_model(model)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 322, in _Popen
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\prune_tiny_yolo.py", line 33, in <lambda>
    return Popen(process_obj)
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
  File "F:\anaconda\envs\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\test.py", line 69, in test
    reduction.dump(process_obj, to_child)
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "F:\anaconda\envs\python36\lib\multiprocessing\reduction.py", line 60, in dump
  File "F:\anaconda\envs\python36\lib\site-packages\tqdm\std.py", line 1093, in __iter__
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
    for obj in iterable:
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "F:\anaconda\envs\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:01<?, ?it/s]
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:00<?, ?it/s]

**Comment by Whatsetsthisend** [comment]
Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "F:\anaconda\envs\python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "F:\anaconda\envs\python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "F:\anaconda\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\prune_tiny_yolo.py", line 38, in <module>
    origin_model_metric = eval_model(model)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\prune_tiny_yolo.py", line 33, in <lambda>
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\test.py", line 69, in test
Traceback (most recent call last):
  File "prune_tiny_yolo.py", line 38, in <module>
    origin_model_metric = eval_model(model)
  File "prune_tiny_yolo.py", line 33, in <lambda>
    eval_model = lambda model:test(model=model,cfg=opt.model_def, data=opt.data_config)
  File "F:\image_work\jianzhi\YOLOv3-complete-pruning-master\test.py", line 69, in test
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "F:\anaconda\envs\python36\lib\site-packages\tqdm\std.py", line 1093, in __iter__
    for batch_i, (imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "F:\anaconda\envs\python36\lib\site-packages\tqdm\std.py", line 1093, in __iter__
    for obj in iterable:
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    for obj in iterable:
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
    return _DataLoaderIter(self)
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
  File "F:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "F:\anaconda\envs\python36\lib\multiprocessing\process.py", line 105, in start
    w.start()
    self._popen = self._Popen(self)
  File "F:\anaconda\envs\python36\lib\multiprocessing\process.py", line 105, in start
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 322, in _Popen
  File "F:\anaconda\envs\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    return Popen(process_obj)
  File "F:\anaconda\envs\python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\anaconda\envs\python36\lib\multiprocessing\reduction.py", line 60, in dump
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "F:\anaconda\envs\python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:00<?, ?it/s]
               Class    Images   Targets         P         R       mAP        F1:   0%|          | 0/108 [00:02<?, ?it/s]

**Comment by Whatsetsthisend** [comment]
您好作者，我已经勉强的解决了该问题，问题可能是在两个地方的线程抢占，导致了错误，我一开始将错误语句放在main（）中保护起来还是出现了莫名的错误，后来我将test.py中Dateloder模块的num_works从一开始min([os.cpu_count(), batch_size, 16]，改成0，让图像可以在主线程读取，解决了这个问题，这样想想也有可能是我电脑本身的问题？

**Comment by GreenTeaHua** [comment]
win10 将test.py中Dateloder模块的num_works从一开始min([os.cpu_count(), batch_size, 16]，改成0

**Comment by courtfu** [comment]
不用改成单线程，加上if __name__ == '__main__':即可

**Comment by MayLelele** [comment]
我也遇到同样的问题，请问是在哪里加上if name == 'main': 呢？
