### ISSUE TITLE
模型剪枝报错了，请问下什么原因

### ISSUE THREAD

**Issue by baidu88vip** [coldlarry/YOLOv3-complete-pruning#32]
Traceback (most recent call last):
  File "normal_prune.py", line 28, in <module>
    model.load_state_dict(torch.load(opt.model, map_location=device)['model'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Darknet:
	size mismatch for module_list.81.Conv2d.weight: copying a param with shape torch.Size([24, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 1024, 1, 1]).
	size mismatch for module_list.81.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for module_list.93.Conv2d.weight: copying a param with shape torch.Size([24, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 512, 1, 1]).
	size mismatch for module_list.93.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for module_list.105.Conv2d.weight: copying a param with shape torch.Size([24, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
	size mismatch for module_list.105.Conv2d.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).

**Comment by AadeIT** [comment]
我也遇到了这个问题，可以说一下解决方案吗？

**Comment by thfylsty** [comment]
您好，我也遇到了这个。请问是怎么解决的呢，是因为稀疏化程度不够？还是我哪里运行出错了。感谢
