### ISSUE TITLE
unable to prune yolov3 spp model. Need help

### ISSUE THREAD

**Issue by joel5638** [coldlarry/YOLOv3-complete-pruning#67]
When I'm running python3 normal_prune.py

I get this error

TypeError: 'MaxPool2d' object is not subscriptable

can someone help? please

**Comment by ridiculousJoe** [comment]
I met this same problem when trying to prune yolov3 tiny model:
```
$ ~/YOLOv3-complete-pruning# python3 normal_prune.py
               Class    Images   Targets         P         R       mAP        F1: 100%|███████████████████████████████████| 52/52 [00:38<00:00,  1.36it/s]
                 all       821  2.03e+03    0.0501     0.861     0.622    0.0947
Threshold should be less than 0.0811.
The corresponding prune ratio is 0.498.
Channels with Gamma value less than 0.0000 are pruned!
               Class    Images   Targets         P         R       mAP        F1: 100%|███████████████████████████████████| 52/52 [00:37<00:00,  1.39it/s]
                 all       821  2.03e+03    0.0501     0.861     0.622    0.0947
Number of channels has been reduced from 3184 to 2388
Prune ratio: 0.250
mAP of the pruned model is 0.6223
layer index:   0         total channel:   16     remaining channel:   16
layer index:   2         total channel:   32     remaining channel:   32
layer index:   4         total channel:   64     remaining channel:   64
layer index:   6         total channel:  128     remaining channel:  127
layer index:   8         total channel:  256     remaining channel:  230
layer index:  10         total channel:  512     remaining channel:  165
layer index:  12         total channel: 1024     remaining channel: 1024
layer index:  13         total channel:  256     remaining channel:  202
layer index:  14         total channel:  512     remaining channel:  278
layer index:  18         total channel:  128     remaining channel:   87
layer index:  21         total channel:  256     remaining channel:  163
Prune channels: 796     Prune ratio: 0.250
Traceback (most recent call last):
  File "normal_prune.py", line 161, in <module>
    pruned_model = prune_model_keep_size(model, prune_idx, CBL_idx, CBLidx2mask)
  File "/root/YOLOv3-complete-pruning/utils/prune_utils.py", line 220, in prune_model_keep_size
    next_conv = pruned_model.module_list[next_idx][0]
TypeError: 'MaxPool2d' object is not subscriptable
```

My settings in `normal_prune.py`:
```
class opt():
    model_def = "cfg/yolov3-tiny-hand.cfg"
    data_config = "cfg/oxfordhand.data"
    model = 'weights/last.pt'

percent = 0.25
```

Seeking help...

**Comment by ZhihangTang** [comment]
Hello,I need to prune yolov3-spp model,and I got this error too.Did you solve it？
