### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Eric3911** [coldlarry/YOLOv3-complete-pruning#77]
author ，ths you souce，we get to used to create model ，the follow erorr：
ConnectionResetError: [Errno 104] Connection reset by peer

Traceback (most recent call last):
  File "train.py", line 479, in <module>
    train()  # train normally
  File "train.py", line 289, in train
    plot_images(imgs=imgs, targets=targets, paths=paths, fname=fname)
  File "/home/anjungang/YOLOv3-complete-pruning-master/utils/utils.py", line 804, in plot_images
    fig = plt.figure(figsize=(10, 10))
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/pyplot.py", line 546, in figure
    **kwargs)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3337, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 876, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/anjungang/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by chengyequn** [comment]
hi,have you solved this problem?

**Comment by CHINAZYANG** [comment]
在utils/utils.py中增加matplotlib.use('Agg'),如下：
import cv2
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
