### ISSUE TITLE
运行代码出现问题

### ISSUE THREAD

**Issue by xupengao** [coldlarry/YOLOv3-complete-pruning#80]
Traceback (most recent call last):
  File "train.py", line 479, in <module>
    train()  # train normally
  File "train.py", line 360, in train
    save_json=final_epoch and epoch > 0 and 'coco.data' in data)
  File "/home/sdu/PycharmProjects/YOLOv3-complete-pruning/test.py", line 199, in test
    maps[c] = ap[i]
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by xupengao** [comment]
只要是二分类训练数据集，就会报错，其他的没问题

**Comment by lesleyping** [comment]
你好，我也遇到了这个问题，请问您解决了吗？

**Comment by lesleyping** [comment]
> 只要是二分类训练数据集，就会报错，其他的没问题

你好，我也遇到了这个问题，请问您解决了吗？
