### ISSUE TITLE
normal_prune.py 问题？

### ISSUE THREAD

**Issue by yurui777** [coldlarry/YOLOv3-complete-pruning#9]
代码：238.行，我加了
            if mtype in ['convolutional', 'upsample', 'maxpool']:
                print(self.module_list[i])
                print(x.shape)
                x = module(x)
error:最相关的最后几行
Sequential(
  (Conv2d): Conv2d(343, 99, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (BatchNorm2d): BatchNorm2d(99, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (activation): LeakyReLU(negative_slope=0.1, inplace=True)
)
torch.Size([16, 343, 52, 52])
Traceback (most recent call last):
  File "normal_prune.py", line 199, in <module>
    compact_forward_time, compact_output = obtain_avg_forward_time(random_input, compact_model)
  File "normal_prune.py", line 192, in obtain_avg_forward_time
    output = model(input)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxxxx/projects/YOLOv3-complete-pruning/models.py", line 241, in forward
    x = module(x)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 99 289 3 3, expected input[16, 343, 52, 52] to have 289 channels, but got 343 channels instead

补充：这层是route(-1,-18)后的卷积层

请问楼主，up主，亲爱的作者，为什么有这个289啊，求解答

**Comment by coldlarry** [comment]
请问您用的是自己的数据集所以报错吗？这个错我没有遇到过，我自己这边按照我写的步骤执行，正常剪枝可以跑的通。------------------ 原始邮件 ------------------
发件人: "Rui Yu"<notifications@github.com>
发送时间: 2019年11月7日(星期四) 晚上8:47
收件人: "coldlarry/YOLOv3-complete-pruning"<YOLOv3-complete-pruning@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [coldlarry/YOLOv3-complete-pruning] normal_prune.py 问题？ (#9)



代码：238.行，我加了
 if mtype in ['convolutional', 'upsample', 'maxpool']:
 print(self.module_list[i])
 print(x.shape)
 x = module(x)
 error:最相关的最后几行
 Sequential(
 (Conv2d): Conv2d(343, 99, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
 (BatchNorm2d): BatchNorm2d(99, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
 (activation): LeakyReLU(negative_slope=0.1, inplace=True)
 )
 torch.Size([16, 343, 52, 52])
 Traceback (most recent call last):
 File "normal_prune.py", line 199, in 
 compact_forward_time, compact_output = obtain_avg_forward_time(random_input, compact_model)
 File "normal_prune.py", line 192, in obtain_avg_forward_time
 output = model(input)
 File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in call
 result = self.forward(*input, **kwargs)
 File "/home/xxxxx/projects/YOLOv3-complete-pruning/models.py", line 241, in forward
 x = module(x)
 File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in call
 result = self.forward(*input, **kwargs)
 File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
 input = module(input)
 File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in call
 result = self.forward(*input, **kwargs)
 File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
 return self.conv2d_forward(input, self.weight)
 File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
 self.padding, self.dilation, self.groups)
 RuntimeError: Given groups=1, weight of size 99 289 3 3, expected input[16, 343, 52, 52] to have 289 channels, but got 343 channels instead
 
补充：这层是route(-1,-18)后的卷积层
 
请问楼主，up主，亲爱的作者，为什么有这个289啊，求解答
 
&mdash;

**Comment by yurui777** [comment]
嗯，我是自己修改的yolov3结构，但是为什么w权重结构会跟module_list[i]不一样呢，module=module_list[i],是不是某一层[route]为多层连接结构导致的bug?

**Comment by coldlarry** [comment]
如果是自己修改了yolov3的结构的话，跑这个代码是跑不通的，因为这是基于标准yolo实现的。如果想跑通，需要修改两个地方：①是train.py中稀疏化训练的层要和你自己想稀疏的层对上 ②normal_prune中，指定了一些固定的层的编号来选择剪枝与否，需要修改这些层。 

我的建议是，可以先把normal_prune大致看懂，这样很快就能解决这个问题。

**Comment by yurui777** [comment]
大致看了的。train里面也改了CBL_idx, Conv_idx, prune_idx，但是训练完成后好像也没有重新生成cfg文件，normal_prune指的是train.py的cfg,一个文件？？请您解答

**Comment by coldlarry** [comment]
normal_prune说的是normal_prune.py,你要在里面修改代码才能支持自己设计的yolo结构能剪枝。

**Comment by ShiHangY** [comment]
when run normal_prune.py have this problem : 

Channels would be all pruned!
Traceback (most recent call last):
  File "prune/normal_prune.py", line 155, in <module>
    num_filters, filters_mask = obtain_filters_mask(model, threshold, CBL_idx, prune_idx)
  File "prune/normal_prune.py", line 137, in obtain_filters_mask
    raise Exception
Exception

**Comment by WY51BE** [comment]
想请问一下，运行了normal_prune.py之后，可以得到对应剪枝后cfg文件的weights文件吗

**Comment by Muxindawang** [comment]
> when run normal_prune.py have this problem :
> 
> Channels would be all pruned!
> Traceback (most recent call last):
> File "prune/normal_prune.py", line 155, in
> num_filters, filters_mask = obtain_filters_mask(model, threshold, CBL_idx, prune_idx)
> File "prune/normal_prune.py", line 137, in obtain_filters_mask
> raise Exception
> Exception

have you solved this problem?
