### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by CHINAZYANG** [coldlarry/YOLOv3-complete-pruning#93]

**Comment by CHINAZYANG** [comment]
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from utils.prune_utils import *
  File "/home/user/zy/YOLOv3-complete-pruning-master/utils/prune_utils.py", line 113
    f.write(f"[{module_def['type']}]\n")
                                      ^
SyntaxError: invalid syntax
